# reckoner-factory-sol — kitty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background              #f6f6f6
foreground              #5b4848
cursor                  #b4460e
cursor_text_color       #f6f6f6
selection_background    #e5dbd7
selection_foreground    #5b4848
url_color               #b4460e

# ANSI 16-color palette
color0                   #e5dbd7
color1                   #ce1c25
color2                   #44744b
color3                   #896020
color4                   #78665e
color5                   #5b4848
color6                   #b4460e
color7                   #5b4848
color8                   #918273
color9                   #ce1c25
color10                  #44744b
color11                  #896020
color12                  #b4460e
color13                  #b4460e
color14                  #b4460e
color15                  #b4460e
