# reckoner-wopr-sol — kitty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background              #eef0f4
foreground              #084c91
cursor                  #096bae
cursor_text_color       #eef0f4
selection_background    #d7dde5
selection_foreground    #084c91
url_color               #096bae

# ANSI 16-color palette
color0                   #d7dde5
color1                   #ae4758
color2                   #1c7744
color3                   #836407
color4                   #366aa5
color5                   #084c91
color6                   #096bae
color7                   #084c91
color8                   #6c88b2
color9                   #ae4758
color10                  #1c7744
color11                  #836407
color12                  #096bae
color13                  #096bb3
color14                  #096bb3
color15                  #096bb3
