# reckoner-scope-sol — kitty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background              #f0f2f0
foreground              #115525
cursor                  #067929
cursor_text_color       #f0f2f0
selection_background    #dae2dc
selection_foreground    #115525
url_color               #067929

# ANSI 16-color palette
color0                   #dae2dc
color1                   #c72d0a
color2                   #115525
color3                   #786811
color4                   #3e754e
color5                   #115525
color6                   #067929
color7                   #115525
color8                   #688d72
color9                   #c72d0a
color10                  #115525
color11                  #786811
color12                  #067929
color13                  #06792a
color14                  #06792a
color15                  #06792a
