# reckoner-exect-sol — kitty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background              #f3f1ef
foreground              #6f4306
cursor                  #8d5d07
cursor_text_color       #f3f1ef
selection_background    #e4dfd8
selection_foreground    #6f4306
url_color               #8d5d07

# ANSI 16-color palette
color0                   #e4dfd8
color1                   #c72a0a
color2                   #4e7326
color3                   #7e6407
color4                   #866127
color5                   #6f4306
color6                   #8d5d07
color7                   #6f4306
color8                   #9d8058
color9                   #c72a0a
color10                  #4e7326
color11                  #7e6407
color12                  #8d5d07
color13                  #8d6007
color14                  #8d6007
color15                  #8d6007
