# reckoner-darkspace-sol — kitty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background              #edf4f4
foreground              #0b5651
cursor                  #067469
cursor_text_color       #edf4f4
selection_background    #d7e4e4
selection_foreground    #0b5651
url_color               #067469

# ANSI 16-color palette
color0                   #d7e4e4
color1                   #b5405c
color2                   #067944
color3                   #786811
color4                   #197670
color5                   #0b5651
color6                   #067469
color7                   #0b5651
color8                   #4a9096
color9                   #b5405c
color10                  #067944
color11                  #786811
color12                  #067469
color13                  #067468
color14                  #067468
color15                  #067468
