# reckoner-dusk-sol — kitty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background              #f0f0f2
foreground              #46496d
cursor                  #774fc5
cursor_text_color       #f0f0f2
selection_background    #dbd9e2
selection_foreground    #46496d
url_color               #774fc5

# ANSI 16-color palette
color0                   #dbd9e2
color1                   #ca164c
color2                   #08719b
color3                   #7f6415
color4                   #616794
color5                   #46496d
color6                   #774fc5
color7                   #46496d
color8                   #88819c
color9                   #ca164c
color10                  #08719b
color11                  #7f6415
color12                  #774fc5
color13                  #7e37f0
color14                  #7e37f0
color15                  #7e37f0
