# reckoner-exect-sol — Ghostty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background = f3f1ef
foreground = 6f4306

cursor-color = 8d5d07
cursor-text = f3f1ef
cursor-style       = block
cursor-style-blink = false

selection-background = e4dfd8
selection-foreground = 6f4306

split-divider-color = f3f1ef
unfocused-split-fill = f3f1ef

minimum-contrast = 1.2

# ANSI 16-color palette
palette = 0=#e4dfd8
palette = 1=#c72a0a
palette = 2=#4e7326
palette = 3=#7e6407
palette = 4=#866127
palette = 5=#6f4306
palette = 6=#8d5d07
palette = 7=#6f4306
palette = 8=#9d8058
palette = 9=#c72a0a
palette = 10=#4e7326
palette = 11=#7e6407
palette = 12=#8d5d07
palette = 13=#8d6007
palette = 14=#8d6007
palette = 15=#8d6007
