# reckoner-darkspace-sol — Ghostty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background = edf4f4
foreground = 0b5651

cursor-color = 067469
cursor-text = edf4f4
cursor-style       = block
cursor-style-blink = false

selection-background = d7e4e4
selection-foreground = 0b5651

split-divider-color = edf4f4
unfocused-split-fill = edf4f4

minimum-contrast = 1.2

# ANSI 16-color palette
palette = 0=#d7e4e4
palette = 1=#b5405c
palette = 2=#067944
palette = 3=#786811
palette = 4=#197670
palette = 5=#0b5651
palette = 6=#067469
palette = 7=#0b5651
palette = 8=#4a9096
palette = 9=#b5405c
palette = 10=#067944
palette = 11=#786811
palette = 12=#067469
palette = 13=#067468
palette = 14=#067468
palette = 15=#067468
