# reckoner-scope-sol — Ghostty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background = f0f2f0
foreground = 115525

cursor-color = 067929
cursor-text = f0f2f0
cursor-style       = block
cursor-style-blink = false

selection-background = dae2dc
selection-foreground = 115525

split-divider-color = f0f2f0
unfocused-split-fill = f0f2f0

minimum-contrast = 1.2

# ANSI 16-color palette
palette = 0=#dae2dc
palette = 1=#c72d0a
palette = 2=#115525
palette = 3=#786811
palette = 4=#3e754e
palette = 5=#115525
palette = 6=#067929
palette = 7=#115525
palette = 8=#688d72
palette = 9=#c72d0a
palette = 10=#115525
palette = 11=#786811
palette = 12=#067929
palette = 13=#06792a
palette = 14=#06792a
palette = 15=#06792a
