# reckoner-factory-sol — Ghostty
# Phosphor theme.
# https://github.com/sainzs/random-access-themes

background = f6f6f6
foreground = 5b4848

cursor-color = b4460e
cursor-text = f6f6f6
cursor-style       = block
cursor-style-blink = false

selection-background = e5dbd7
selection-foreground = 5b4848

split-divider-color = f6f6f6
unfocused-split-fill = f6f6f6

minimum-contrast = 1.2

# ANSI 16-color palette
palette = 0=#e5dbd7
palette = 1=#ce1c25
palette = 2=#44744b
palette = 3=#896020
palette = 4=#78665e
palette = 5=#5b4848
palette = 6=#b4460e
palette = 7=#5b4848
palette = 8=#918273
palette = 9=#ce1c25
palette = 10=#44744b
palette = 11=#896020
palette = 12=#b4460e
palette = 13=#b4460e
palette = 14=#b4460e
palette = 15=#b4460e
